name: build
on:
  push:
    branches: [ main, feature/*, bugfix/* ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Checkout badges branch to a badges directory nested inside first checkout
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Badge To Path
        uses: janpk/badge-to-path@main
        with:
          label: Test
          status: Success
          path: badges/test.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./mvnw verify -B
      - name: Commit the badge (if it changed)
        if: github.ref == 'refs/heads/main'
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.email "vampyr.geistlig_0j@icloud.com"
            git config --global user.name "Badge Gen"
            git add *.svg
            git commit -m "Autogenerated badge" --allow-empty
            git push
          fi

