name: build
on:
  push:
    branches: [ main, feature/*, bugfix/* ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Badge To Path
        uses: janpk/badge-to-path@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./mvnw verify -B

